# Generated by Django 5.0.1 on 2024-02-19 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0003_tag_apostila_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('apostila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apostilas.apostila')),
            ],
        ),
    ]
